### ISSUE TITLE
Higher category objects and descriptive vocabulary

### ISSUE THREAD

**Issue by MatthiasCami8** [facebookresearch/Detic#38]
Thanks for publishing this paper, I had 2 questions:

-When using an image of different kind of fruits/vegetables, with a vocabulary such as LVIS, the model nicely detects all specific categories. However, when using a custom vocabulary and looking for "fruits, vegetables" it does not detect anything at all, even though you would expect the embedding of the word "fruit" be close to "apple", so why is it not working when using higher category objects? The same thing goes for example when detecting "cat, dog" vs "animal".

-When using a simple image of for example a person sitting on a bench and using custom voc "a person sitting on a bench", it only selects the bench. The same goes with any kind of similar description tasks (even color descriptions like "red car"). I tried different prompts for prompt engineering but did not find a solution, even though CLIP on itself should be able to do this?

Thanks for your help!

**Comment by xingyizhou** [comment]
Hi,

  Thank you for the nice questions and interesting insights!

  1. I am not excepting this but it might happen because we did not handle the label hierarchies in training. I.e., if the vocabulary has both `cat` and `animal`, `animal` will be a negative class if the annotation is `cat`. We briefly studied the label hierarchy problem in our [UniDet project](https://github.com/xingyizhou/UniDet/blob/master/projects/UniDet/configs/OID_CRFR50_CAS_2x.yaml#L10) and used a hierarchical-aware loss to handle it. We did not use it in Detic.
  2. This is a great direction! Currently, I am not expecting Detic to work for referring expressions as we never modeled object relations. `Red car` is also less likely to work because `red car` itself is not a class in ImageNet. In our [Appendix C](https://arxiv.org/pdf/2201.02605.pdf), we studied directly using captions as supervision, which might have a better chance of getting color or more sophisticated object descriptions. However we did not include direct caption supervision in our final model.

Best,
Xingyi
