### ISSUE TITLE
Possible access to IN-L and CC dataset

### ISSUE THREAD

**Issue by Dwrety** [facebookresearch/Detic#52]
Thank you for sharing your work! Is it possible that you provide a separate link to directly download the preprocessed IN-L and CC split that shares the same vocabulary with LVIS? Especially for Imagenet21K, the fall21 split is no longer available from the official sites. Also there are multiple image urls no longer available for CC anymore.

**Comment by xingyizhou** [comment]
Hi,

  Unfortunately, we are not able to preprocessed data files due to dataset license issues. I personally believe there should be little difference between fall21 and the other vision. You can check the overlapping vocabulary [here](https://github.com/facebookresearch/Detic/blob/main/configs/Detic_ViLD_200e.py#L131). Please let me know if there is a difference. Please also let me know if you observe there is a significant performance drop when using the available version compared to our paper.

Best,
Xingyi

**Comment by Dwrety** [comment]
Got it. Thank you
